baseurl = "https://www.rgray.co.uk" # Hostname (and path) to the root.
title = "Ross Gray" # Site title.
theme = "dev" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = false # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

# disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Ross Gray" # Author's name.
    info = "Full Stack Software Developer" # Author's job title or info.
    description = "Ross Gray's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    # footercontent = "Enter some text here." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/rossgray/"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 2
    url = "https://stackoverflow.com/story/rossgray"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/rossgray1/"
#[[params.social]]
#    name = "Twitter"
#    icon = "fab fa-twitter fa-2x"
#    weight = 4
#    url = "https://twitter.com/rossgray/"